### PR TITLE
Update 05-create-profiles.Rmd

### PR DESCRIPTION
**Pull request by bethac07**

### CODE REVIEW

**Comment by bethac07** [comment]
@shntnu @niranjchandrasekaran Do you guys prefer me to pull this with the open todos for Niranj, or do you want to go through and do that first before I pull?

**Comment by niranjchandrasekaran** [comment]
@bethac07 This slipped through the cracks. I will complete my todos this week and then you can pull

**Comment by niranjchandrasekaran** [comment]
@bethac07 I have added some text about external metadata. Let me know if I need to add more.

**Comment by bethac07** [comment]
Looks great to me, thanks (and thanks for catching that last hardcoding)!  Should we go ahead and pull?

**Pull request merged**
