### PR TITLE
Convert to jupyter-book

### PR DESCRIPTION
**Pull request by callum-jpg**
Changes made:
- Authors are now shown at the bottom of every page
- ToC parts are defined in `_toc.yml` rather than inside `.Rmd` files themselves
- Added 'Getting Started' to first part in ToC
- Instead of subsections (define by ##, ### etc.) being shown in the left ToC pane, they are shown in the right pane upon selection of a particular chapter
	- I think to have subsections shown in the left pane would require each subsection to be a distinct file
- All files were converted from `.Rmd` to `.md` 
	- This was because the best way to replace the 'note' sections (eg in `03-setup-images.md` was to use the jupyter-book ```{note}``` directive
		- However, this directive isn't available for `.Rmd` files converted with jupytex it seems, hence the conversion
- Changing to `.md` alters the method for lists and linking to other pages, which have also been updated
- Paragraphs of text added to one line
- Can't find a replacement for appendix specific numbering 
	- eg A1, A2 etc.
- `gh-pages` branch (and therefore the website) will be updated on any pushes to master branch by github actions

### CODE REVIEW

**Comment by bethac07** [comment]
You can check out what it looks like on his fork [here](https://callum-jpg.github.io/profiling-handbook/index.html)

**Comment by bethac07** [comment]
@shntnu Ok to just go ahead and pull this?

**Review by bethac07 — APPROVED** [review]

**Comment by bethac07** [comment]
Actually @callum-jpg  looks like you forked off the next to last commit, we need to rebase this onto [the last commit](https://github.com/cytomining/profiling-handbook/commit/d9b9f5afbe50d631a99fe3121c6c4fbeb288a979). If you need help, happy to have you throw time on my calendar!

**Comment by shntnu** [comment]
> @shntnu Ok to just go ahead and pull this?

Yes, certainly! 

Over to @callum-jpg and you https://github.com/cytomining/profiling-handbook/pull/66#issuecomment-1085916815

**Pull request merged**
