### PR TITLE
lfs => dvc

### PR DESCRIPTION
**Pull request by ErinWeisbart**
Updates the handbook to reflect [recent changes to the profiling-recipe](https://github.com/cytomining/profiling-recipe/pull/25) wherein we switch from the use of Git LFS to DVC for large file management.

### CODE REVIEW

**Comment by shntnu** [comment]
I can fix this build error, but I wonder if this is the right time to do the thing @bethac07 suggested below.

Over to you two to decide @ErinWeisbart @bethac07 

----------
From: Beth Cimini <bcimini@broadinstitute.org>
Date: Tue, Nov 30, 2021 at 6:49 AM
To: Shantanu Singh <shsingh@broadinstitute.org>


FWIW, I don't think the "lift" is currently probably worth it, but if we did want to switch to JupyterBook somewhere down the road, it looks like it takes Rmd pages so it would be a fast start-up.

https://jupyterbook.org/file-types/jupytext.html?highlight=rmd


----------
From: Shantanu Singh <shsingh@broadinstitute.org>
Date: Tue, Nov 30, 2021 at 6:56 AM
To: Beth Cimini <bcimini@broadinstitute.org>


Neat! The conversion would be a nice project (~2-3 days?) for someone who is interested in creating training material and learning about GitHub Actions.




----------
From: Beth Cimini <bcimini@broadinstitute.org>
Date: Tue, Nov 30, 2021 at 7:11 AM
To: Shantanu Singh <shsingh@broadinstitute.org>


Since it can read Rmd files directly, and GH actions is already documented, assuming we stuck with the Rmd files we have in theory it's a 30 minute project; someone with not a ton of experience still could probably get it up and running in a day. 

It doesn't look like there are any good tools (ala pandoc) for a straight Rmd-to-MyST conversion, but with the VSCode extensions for Rmd and for MyST both installed and a MyST cheat sheet, I still can't see it taking much more than a few hours.


----------
From: Shantanu Singh <shsingh@broadinstitute.org>
Date: Tue, Nov 30, 2021 at 7:15 AM
To: Beth Cimini <bcimini@broadinstitute.org>


Good point – just 6 Rmd files, and it's mostly just the code blocks that will need conversion (if done by hand)

**Comment by bethac07** [comment]
@ErinWeisbart your call; we can discuss at checkin today if you need more info

**Comment by bethac07** [comment]
Otherwise, I would say might be a good project for Callum since a) he's working on CellProfiler so he's going to need to know a bit about GHActions for build stuff and b) he's planning on putting together the documentation for Piximi in Jupyter book and so having an easy starter project for that might be good practice.

**Comment by bethac07** [comment]
Callum has said he's happy to work on this next week, so let's maybe just pull this and make a separate GH issue for the migration?

**Comment by bethac07** [comment]
@ErinWeisbart you're also welcome to work on this too, or we can all work on it together, not trying to take it if you're interested :)

**Comment by ErinWeisbart** [comment]
I've got plenty on my plate at the moment and I'm happy to have Callum handle the integration.

**Comment by bethac07** [comment]
I'm going to go ahead and merge then, and move the changing the build to a new issue.

**Pull request merged**
